In [79]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy
from sympy import *
from jupyterthemes import jtplot
import math
jtplot.style()

# Exercises

## 4.1
Compute the determinant using the Laplace expansion (using the first row) and the Sarrus rule for $$\mathbf{A} = \begin{bmatrix}
1&3&5 \\
2&4&6 \\
0&2&4 \end{bmatrix} $$

Using the Laplace expansion along the first row:

$ \begin{vmatrix}
1&3&5 \\
2&4&6 \\
0&2&4 \end{vmatrix} = -(1)^{1 +1}1 \begin{vmatrix}
4&6 \\ 
2&4 \end{vmatrix} + (-1)^{1+2}3\begin{vmatrix}
2&6 \\
0&4 \end{vmatrix}+ (-1)^{1+3}5\begin{vmatrix}
2&4 \\
0&2 \end{vmatrix}$




det ($A$) $ = 1 (16 - 12) - 3 (8 - 0) + 5(4 - 0)$

$ = 4 - 24 + 20 = 0 $

Using Sarrus' rule:

det($A$) $= (1*4*4) + (2*2*5) + (3*6*0) - (0*4*5) - (2*6*1) - (4*2*3) $

$ = 16 + 20 + 0 - 0 - 12 - 24 = 0$

In [80]:
# check
A = np.array([[1, 3, 5],[2, 4, 6], [0, 2, 4]]).reshape(3, 3)
np.linalg.det(A)

0.0

## 4.2
Compute the following determinant efficiently: 
$$\begin{bmatrix}
2&0&1&2&0 \\
2&-1&0&1&1 \\
0&1&2&1&2 \\
-2&0&2&-1&2 \\
2&0&0&1&1 \end{bmatrix}$$

Get into ref:

$$\begin{vmatrix}
2&0&1&2&0 \\
2&-1&0&1&1 \\
0&1&2&1&2 \\
-2&0&2&-1&2 \\
2&0&0&1&1 \end{vmatrix} \begin{matrix}
\longrightarrow \\
-R_1 + R_2 \backsim R_2 \\
R_1 + R_4 \backsim R_4 \\
-R_1 + R_5 \backsim R_5 \end{matrix}\begin{vmatrix}
2&0&1&2&0 \\
0&-1&-1&-1&1 \\
0&1&2&1&2 \\
0&0&3&1&2 \\
0&0&-1&-1&1 \end{vmatrix}\begin{matrix}
\longrightarrow \\
R_2 + R_3 \backsim R_3 \end{matrix}\begin{vmatrix}
2&0&1&2&0 \\
0&-1&-1&-1&1 \\
0&0&1&0&3 \\
0&0&3&1&2 \\
0&0&-1&-1&1 \end{vmatrix}$$

$$\begin{matrix}
\longrightarrow \\
-3R_3 + R_4 \backsim R_4 \\
R_3 + R_5 \backsim R_5 \end{matrix}\begin{vmatrix}
2&0&1&2&0 \\
0&-1&-1&-1&1 \\
0&0&1&0&3 \\
0&0&0&1&-7 \\
0&0&0&-1&4 \end{vmatrix}\begin{matrix}
\longrightarrow \\
R_4 + R_5 \backsim R_5 \end{matrix}\begin{vmatrix}
2&0&1&2&0 \\
0&-1&-1&-1&1 \\
0&0&1&0&3 \\
0&0&0&1&-7 \\
0&0&0&0&-3 \end{vmatrix}$$

Since our matrix is now in upper-right triangular form, the determinant is the product of it's diagonal:

$(2)(-1)(1)(1)(-3) = 6 $

In [81]:
# put matrix into row-eschelon form (note this results in an upper-triangluar matrix as the matrix is square)
U = np.array([[2, 0, 1, 2, 0], [2, -1, 0, 1, 1], [0, 1, 2, 1, 2], [-2, 0, 2, -1, 2], [2, 0, 0, 1, 1]]).reshape(5, 5)
print('determinant of full matrix :', round(np.linalg.det(U), 2))

determinant of full matrix : 6.0


## 4.3
Compute the eigenspaces of  
__a__. $$ \mathbf{A} := \begin{bmatrix}
1&0 \\
1&1 \end{bmatrix} $$

Characteristic Polynomial

$p_A(\lambda) = det (A - \lambda I) $ 

$= det \Bigl(\begin{bmatrix}
1&0 \\
1&1 \end{bmatrix} - \begin{bmatrix}
\lambda&0 \\
0&\lambda \end{bmatrix}\Bigr) = \begin{vmatrix}
1 - \lambda & 0 \\
1 & 1 - \lambda \end{vmatrix} = (1 - \lambda)^2 - 0$

$p(\lambda) = (1 - \lambda)^2$, which gives us the roots of $\lambda_1 = \lambda_2 = 1 $. Putting the equation in the form of $ \begin{bmatrix}
1 - \lambda & 0 \\
1 & 1 - \lambda \end{bmatrix}\mathbf{x} = \mathbf{0}$. 

Plugging this back into our matrix to find the eigenspaces, we get 
$\begin{bmatrix}
0&0 \\
1&0 \end{bmatrix}\begin{bmatrix}
x_1 \\
x_2 \end{bmatrix} = \begin{bmatrix}
0 \\
0 \end{bmatrix}$

$0x_1 + 0x_2 = 0$  
$1x_1 + 0x_2 = 0$

$ x_1 $ must be $0$, $x_2$ is a scalar &rarr; $\begin{bmatrix}
1&0 \\
1&1 \end{bmatrix}\begin{bmatrix}
0 \\
c \end{bmatrix} = \begin{bmatrix}
0 \\
c \end{bmatrix}$ where $c$ is a scalar.

The eigenspaces of $A$ are $E_{span}\bigl(\begin{bmatrix}
0 \\
c \end{bmatrix}\bigr)$

In [82]:
A = np.array([[1, 0], [1, 1]]).reshape(2, 2)
eig_val, eig_vec = np.linalg.eig(A)
print(np.round(eig_vec))

[[ 0.  0.]
 [ 1. -1.]]


__b__. $$ \mathbf{B} := \begin{bmatrix}
-2&2 \\
2&1 \end{bmatrix} $$

As above

$p_B(\lambda) = det (B - \lambda I) $ 

$= det \Bigl(\begin{bmatrix}
-2&2 \\
2&1 \end{bmatrix} - \begin{bmatrix}
\lambda&0 \\
0&\lambda \end{bmatrix}\Bigr) = \begin{vmatrix}
-2 - \lambda & 2 \\
2 & 1 - \lambda \end{vmatrix} = (-1)(2 + \lambda)(1 - \lambda) - 4$  

Factoring this out yields:  
$(\lambda - 2)(\lambda + 3)$ So we have roots $ \lambda_1 = 2, \lambda_2 = -3$

$\begin{bmatrix}
-2 - 2 & 2 \\
2 & 1 - 2 \end{bmatrix} \begin{bmatrix}
x_1 \\
x_2 \end{bmatrix} = \begin{bmatrix}
0 \\
0 \end{bmatrix}$

$-4x_1 + 2x_2 = 0 $  
$2x_1 - x_2 = 0 $  
Solving yields $x_2$ to be a free variable, so we get E_2 = $2\begin{bmatrix}
0.5 \\
1 \end{bmatrix}$

$\begin{bmatrix}
-2 - (-3) & 2 \\
2 & 1 - (-3) \end{bmatrix} \begin{bmatrix}
x_1 \\
x_2 \end{bmatrix} = \begin{bmatrix}
0 \\
0 \end{bmatrix}$

$1x_1 + 2x_2 = 0 $  
$2x_1 + 4x_2 = 0 $  
Similarly setting $x_2$ to be a free variable, we get E_{-3} = $-3\begin{bmatrix}
-2 \\
1 \end{bmatrix}$

In [83]:
B = np.array([[-2, 2], [2, 1]]).reshape(2, 2)
eig_val, eig_vec = np.linalg.eig(B)
print(eig_val)
print(eig_vec)

[-3.  2.]
[[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]


## 4.4 
Compute all the eigenspaces of $$ \mathbf{A} = \begin{bmatrix}
0&-1&1&1 \\
-1&1&-2&3 \\
2&-1&0&0 \\
1&-1&1&0 \end{bmatrix} $$

In [84]:
A = np.array([[0, -1, 1, 1], [-1, 1, -2, 3], [2, -1, 0, 0], [1, -1, 1, 0]]).reshape(4, 4)
eig_val, eig_vec= np.linalg.eig(A)
print(np.round(eig_vec))
print(np.round(eig_val))

[[ 1.+0.j  1.+0.j -0.-0.j -0.+0.j]
 [ 0.+0.j  0.+0.j -1.+0.j -1.-0.j]
 [ 1.+0.j  1.+0.j -1.+0.j -1.-0.j]
 [ 1.+0.j  1.+0.j  0.+0.j  0.-0.j]]
[ 2.+0.j  1.+0.j -1.+0.j -1.-0.j]


## 4.5
Diagonalizability of a matrix is unrelated to its invertibility. Determine for the following four matrices whether they are diagonalizable and/or invertible. 

*Diagonalizable* -- A symmetric matrix is always diagonalizable. A non-symmetric square matrix is diagonalizable if it contains n linearly independent eigenvectors. 

*Invertible* -- A square matrix is invertible if it's determinant does not equal 0.

$$ \begin{bmatrix}
1&0 \\
0&1 \end{bmatrix},  \begin{bmatrix}
1&0 \\
0&0 \end{bmatrix}, \begin{bmatrix}
1&1 \\
0&1 \end{bmatrix}, \begin{bmatrix}
0&1 \\
0&0 \end{bmatrix}$$

In [85]:
matrix = np.array([[1,0], [0,1]]).reshape(2, 2)
display(Matrix(matrix))
print('determinant: ', np.linalg.det(matrix))
eig_val, eig_vec = np.linalg.eig(matrix)
I = np.diag(np.ones(len(eig_val)))
D = I * np.round(eig_val,2)

print('eigenvalues:\n', eig_val)
print('eigenvectors:\n', np.round(eig_vec))
print('PDP.T:\n', np.round(np.dot(eig_vec, (np.dot(D, eig_vec.T)))))
print(np.linalg.matrix_rank(eig_vec))
# Invertible 
# diagonalizable

Matrix([
[1, 0],
[0, 1]])

determinant:  1.0
eigenvalues:
 [1. 1.]
eigenvectors:
 [[1. 0.]
 [0. 1.]]
PDP.T:
 [[1. 0.]
 [0. 1.]]
2


In [86]:
matrix = np.array([[1,0], [0,0]]).reshape(2, 2)
display(Matrix(matrix))
print('determinant: ', np.linalg.det(matrix))
eig_val, eig_vec = np.linalg.eig(matrix)
I = np.diag(np.ones(len(eig_val)))
D = I * np.round(eig_val,2)

print('eigenvalues:\n', eig_val)
print('eigenvectors:\n', np.round(eig_vec))
print('PDP.T:\n', np.round(np.dot(eig_vec, (np.dot(D, eig_vec.T)))))
print(np.linalg.matrix_rank(eig_vec))
# NOT invertible
# Diagonizable

Matrix([
[1, 0],
[0, 0]])

determinant:  0.0
eigenvalues:
 [1. 0.]
eigenvectors:
 [[1. 0.]
 [0. 1.]]
PDP.T:
 [[1. 0.]
 [0. 0.]]
2


In [87]:
matrix = np.array([[1,1], [0,1]]).reshape(2, 2)
display(Matrix(matrix))
print('determinant: ', np.linalg.det(matrix))
eig_val, eig_vec = np.linalg.eig(matrix)
I = np.diag(np.ones(len(eig_val)))
D = I * np.round(eig_val,2)

print('eigenvalues:\n', eig_val)
print('eigenvectors:\n', np.round(eig_vec))
print('PDP.T:\n', np.round(np.dot(eig_vec, (np.dot(D, eig_vec.T)))))
print(np.linalg.matrix_rank(eig_vec))
# invertible
# NOT diagonalizable

Matrix([
[1, 1],
[0, 1]])

determinant:  1.0
eigenvalues:
 [1. 1.]
eigenvectors:
 [[ 1. -1.]
 [ 0.  0.]]
PDP.T:
 [[ 2. -0.]
 [-0.  0.]]
1


In [88]:
matrix = np.array([[0,1], [0,0]]).reshape(2, 2)
display(Matrix(matrix))
print('determinant: ', np.linalg.det(matrix))
eig_val, eig_vec = np.linalg.eig(matrix)
I = np.diag(np.ones(len(eig_val)))
D = I * np.round(eig_val,2)

print('eigenvalues:\n', eig_val)
print('eigenvectors:\n', np.round(eig_vec))
print('PDP.T:\n', np.round(np.dot(eig_vec, (np.dot(D, eig_vec.T)))))
print(np.linalg.matrix_rank(eig_vec))
# NOT invertible
# NOT diagonalizable 

Matrix([
[0, 1],
[0, 0]])

determinant:  0.0
eigenvalues:
 [0. 0.]
eigenvectors:
 [[ 1. -1.]
 [ 0.  0.]]
PDP.T:
 [[0. 0.]
 [0. 0.]]
1


## 4.6
Compute the eigenspaces of the following transformation matrices. Are they diagonalizable?  
__a__. For $$ \mathbf{A} = \begin{bmatrix}
2&3&0 \\
1&4&3 \\
0&0&1 \end{bmatrix} $$

In [49]:
A = np.array([[2, 3, 0], [1, 4, 3], [0, 0, 1]]).reshape(3, 3)
eig_val, eig_vec = np.linalg.eig(A)
print('eigenvectors:\n', np.round(eig_vec))
I = np.diag(np.ones(len(eig_val)))
D = I * np.round(eig_val,2)

print('eigenvalues:\n', eig_val)
print('eigenvectors:\n', np.round(eig_vec))
print('PDP.T:\n', np.round(np.dot(eig_vec, (np.dot(D, eig_vec.T)))))
print(np.linalg.matrix_rank(eig_vec))
# NOT diagonalizable 

eigenvectors:
 [[-1. -1.  1.]
 [ 0. -1. -0.]
 [ 0.  0.  0.]]
eigenvalues:
 [1. 5. 1.]
eigenvectors:
 [[-1. -1.  1.]
 [ 0. -1. -0.]
 [ 0.  0.  0.]]
PDP.T:
 [[ 4.  2.  0.]
 [ 2.  3. -0.]
 [ 0. -0.  0.]]
2


__b__. For $$ \mathbf{A} = \begin{bmatrix}
1&1&0&0 \\
0&0&0&0 \\
0&0&0&0 \\
0&0&0&0 \end{bmatrix} $$

In [58]:
A = np.array([[1, 1, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]).reshape(4, 4)
display(Matrix(A))
eig_val, eig_vec = np.linalg.eig(A)
print('eigenvectors:\n', np.round(eig_vec))
I = np.diag(np.ones(len(eig_val)))
D = I * np.round(eig_val)

print('eigenvalues:\n', eig_val)
print('eigenvectors:\n', np.round(eig_vec))
print('PDP.T:\n', np.round(np.dot(eig_vec, (np.dot(D, eig_vec.T)))))
print(np.linalg.matrix_rank(eig_vec))
# Diagonalizable 

Matrix([
[1, 1, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0]])

eigenvectors:
 [[ 1. -1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
eigenvalues:
 [1. 0. 0. 0.]
eigenvectors:
 [[ 1. -1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
PDP.T:
 [[1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
4


## 4.7
Are the following matrices diagonalizable? If yes, determine their diagonal form and a basis with respect to which the transformation matrices are diagonal. If no, give reasons why they are not diagonalizable.

a.

$$\mathbf{A} = \begin{bmatrix}
0&1 \\
-8&4 \end{bmatrix}$$

In [75]:
A = np.array([[0, 1],[-8, 4]]).reshape(2, 2)
eig_val, eig_vec = np.linalg.eig(A)
print('rank of eigenspaces', np.linalg.matrix_rank(eig_vec))
D = np.diag(np.round(eig_val))
basis = np.round(eig_vec)
# not diagonalizable in this dimension

rank of eigenspaces 2


In [77]:
print("b.")
A = np.array([[1, 1, 1],[1, 1, 1], [1, 1, 1]]).reshape(3, 3)
display(Matrix(A))
eig_val, eig_vec = np.linalg.eig(A)
print('eigenvectors:\n', np.round(eig_vec))
I = np.diag(np.ones(len(eig_val)))
D = I * np.round(eig_val)

print('eigenvalues:\n', np.round(eig_val))
print('PDP.T:\n', np.round(np.dot(eig_vec, (np.dot(D, eig_vec.T)))))

b.


Matrix([
[1, 1, 1],
[1, 1, 1],
[1, 1, 1]])

eigenvectors:
 [[-1.  1.  0.]
 [ 0.  1. -1.]
 [ 0.  1.  1.]]
eigenvalues:
 [-0.  3.  0.]
PDP.T:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


c.

In [78]:
A = np.array([[5, 4, 2, 1],[0, 1, -1, -1], [-1, -1, 3, 0], [1, 1, -1, 2]]).reshape(4, 4)
eig_val, eig_vec = np.linalg.eig(A)
print('eigenvectors:\n', np.round(eig_vec))
I = np.diag(np.ones(len(eig_val)))
D = I * np.round(eig_val)

print('eigenvalues:\n', np.round(eig_val))
print(np.dot(eig_vec, np.dot(D, eig_vec.T)).astype(int))

print(np.linalg.matrix_rank(eig_vec))
print(np.linalg.matrix_rank(A))
# not diagonalizable

eigenvectors:
 [[-1.  1. -1. -1.]
 [ 0.  0.  1.  1.]
 [ 1. -1.  0.  0.]
 [-1.  1.  0. -1.]]
eigenvalues:
 [4. 4. 1. 2.]
[[ 3 -1 -2  3]
 [-1  1  0  0]
 [-2  0  2 -2]
 [ 3  0 -2  3]]
3
4
